Demote augeas-tools to Suggests
and let the systemd2init tool error out if /usr/bin/augtool is not
installed.

diff --git a/systemd2init/systemd2init b/systemd2init/systemd2init
--- a/systemd2init/systemd2init
+++ b/systemd2init/systemd2init
@@ -63,7 +63,15 @@ getenvironment() {
     [ -n "$RET" ] && echo $RET
 }
 
-[ -z "$1" ] && echo "usage: $0 <name>" && exit 1
+if [ -z "$1" ]; then
+    echo "usage: $0 <name>"
+    exit 1
+fi
+
+if ! [ -x /usr/bin/augtool ]; then
+    echo "augtool not found, please install augeas-tools"
+    exit 1
+fi
 
 NAME=$1
 
